### PR TITLE
Update MonkeyCache to 2.0 and use System.Text.Json

### PR DESCRIPTION
**Pull request by eerhardt**
- Drop Newtonsoft and use System.Text.Json instead
    - Allow for source generators to be used in IBarrel
- Drop Xamarin TFMs and just target net6.0
- Mark MonkeyCache assemblies as IsTrimmable=true, so unused code can be trimmed

@jamesmontemagno

### CODE REVIEW

**Comment by jamesmontemagno** [comment]
@eerhardt  we should probably write some docs on this.....

**Comment by eerhardt** [comment]
Definitely can do. Do we have docs for MonkeyCache somewhere? The root Readme good enough?

**Comment by jamesmontemagno** [comment]
Yeah rams is good enough:)

**Comment by davidbuckleyni** [comment]
Why their are some nice additions in netown soft why do companies not reach out to developers first before removing stuff

**Comment by eerhardt** [comment]
@davidbuckleyni - can you explain a little bit more?

You can still use Newtonsoft to serialize your objects yourself and put them into the Barrel as `string`.

The biggest reasons for moving to System.Text.Json in this library are:

1. When using Blazor components in Maui, ASP.NET is already using System.Text.Json. So you are paying double for Json serialization size. In the .NET Podcasts app, using this change reduces the app size by over 10%. See https://github.com/microsoft/dotnet-podcasts/pull/58.
2. You can use Source Generation for JSON serialization and deserialization. See https://devblogs.microsoft.com/dotnet/try-the-new-system-text-json-source-generator/ for more details on all the advantages this gives you.

Newtonsoft does have capabilities that System.Text.Json doesn't. But the issue with keeping a reference to Newtonsoft is that Newtonsoft isn't marked as a "Trimmable" assembly. So if you reference it anywhere in your app (even if the code referencing it is trimmed), the whole assembly and anything it references are preserved in your app. This causes bloat in your apps.

**Pull request merged**
