### PR TITLE
Added Support for GetAllKeys() API

### LINKED ISSUE #47: Request: Barrel.Current.GetAllKeys()
First, is it possible to get all the keys that are stored in the cache?

When having large lists which needs paging, I cache the pages with a key and append the page number on the end. For example `$"{MyListCache}{PageNumber}";`

However when I want to refresh the pages, I want to remove all the keys which include the text `MyListCache`.

Therefor I would like to get all the keys, determine if they start with my `MyListCache` key then remove them.

### PR DESCRIPTION
**Pull request by ahoefling**
## Description
Added new API for GetAllKeys() which works across the implementations:

* SQLite
* FileStore
* LiteDB

## Tests
Added new button to the Xamarin.Forms test app to verify new functionality

Fixes #47

### CODE REVIEW

**Comment by ahoefling** [comment]
No Problem.

I added both positive and a negative test cases to cover the new code that was added. While working on this I started to question how should we handle expired keys vs non-expired keys. Right now it just uses the default data structure and doesn't check expiration at all. Not sure if you would like that addressed in this PR or not. As the title suggest this returns ALL keys and doesn't check any expiration DateTimes.

**Comment by jamesmontemagno** [comment]
So hmmm yeah probably some configuration would be good... i am assuming that people will want to get All, Expired, NotExpired? :( hmmmm before I pull in we should think about what else we need.

**Comment by ahoefling** [comment]
Maybe we can have the method take an enum with a default of NotExpired?

**Comment by jamesmontemagno** [comment]
probably... or "GetExpiredKeys" and GetValidKeys" or something?

**Comment by ahoefling** [comment]
I personally like the optional enum flag approach. It makes it super easy to extend and doesn't make the API verbose.  Both approaches are going to work, the question I have is do we want to have 3 methods or 1 method for this 1 API?

* GetAllKeys
* GetExpiredKeys
* GetValidKeys

vs.

* GetAllKeys

Another note on the enum approach. If someone is writing some generic system leveraging this API they wouldn't have to adjust their code for this. They could just pass the enum flag which would simplify their implementation.

Let me know which solution you want me to implement and I'll update the PR

**Comment by jamesmontemagno** [comment]
I think:

Enum
```public 
[Flags]
public enum CacheState
{
    Expired = 1
    Active = 2
}
```

Method: 
```csharp
public IEnumerable<string> GetKeys(CacheState state)
{
}
```

Usage:

var keys = GetKeys(CacheState.Active | CacheState.Expired);


I am going between Active and Valid.....

**Comment by ahoefling** [comment]
I personally like Active and I am going to add `All = 3` so you can get everything.

I'll update the PR later tonight

**Comment by jamesmontemagno** [comment]
No need to do all since it is a flag the dev would just pass in: CacheState.Active | CacheState.Expired

Setting up 'All' wouldn't allow us to add more in the future really.

**Comment by ahoefling** [comment]
That is true, didn't think of passing it with the `|`. I didn't get to it tonight, but I'll update it tomorrow

**Comment by ahoefling** [comment]
This should do it. I added some more unit tests in to cover the 3 scenarios:
* Active
* Expired
* All - using the pipe we discussed `CacheState.Active | CacheState.Expired`

Let me know if there is anything else you need from me before merging

**Pull request merged**
